# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Services\API\LOL\DataDragon\GeneralApi:
        public: true

    App\Services\API\LOL\DataDragon\ItemApi:
        public: true

    App\Services\API\LOL\DataDragon\SummonerApi:
        public: true

    App\Services\API\LOL\DataDragon\ChampionApi:
        public: true
    
    App\Services\API\LOL\MatchApi:
        public: true

    App\Services\API\LOL\LeagueApi:
        public: true

    App\Services\API\LOL\StatusApi:
        public: true

    App\Services\API\LOL\SummonerApi:
        public: true

    App\Services\API\LOL\ChampionRotationApi:
        public: true

    App\Services\API\LOL\ChampionMasteryApi:
        public: true

    App\Services\API\LOL\BaseApi:
        arguments:
            $platform : '%env(string:PLATFORM)%'
            $apiKey: '%env(string:APIKEY)%'
